CREATE TYPE public.app_role AS ENUM ('admin','moderator','user');

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$ BEGIN NEW.updated_at=now(); RETURN NEW; END $$;

CREATE TABLE public.profiles (id uuid PRIMARY KEY,email text,first_name text,last_name text,display_name text,bio text,phone text,gender text,age integer,timezone text NOT NULL DEFAULT 'UTC',avatar_url text,onboarded boolean NOT NULL DEFAULT false,onboarded_at timestamptz,last_seen_at timestamptz,sign_in_count integer NOT NULL DEFAULT 0,avg_study_hours numeric,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY profiles_own ON public.profiles FOR ALL TO authenticated USING(auth.uid()=id) WITH CHECK(auth.uid()=id);

CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,role public.app_role NOT NULL DEFAULT 'user',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY user_roles_read_own ON public.user_roles FOR SELECT TO authenticated USING(auth.uid()=user_id);
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role)$$;

CREATE TABLE public.app_settings (id boolean PRIMARY KEY DEFAULT true CHECK(id),site_name text NOT NULL DEFAULT 'Chronodeck Study OS',tagline text NOT NULL DEFAULT 'Study smarter, every day',support_email text,banner_text text,ai_enabled boolean NOT NULL DEFAULT true,manual_log_enabled boolean NOT NULL DEFAULT true,landing_enabled boolean NOT NULL DEFAULT true,maintenance_note text,signup_enabled boolean NOT NULL DEFAULT true,google_auth_enabled boolean NOT NULL DEFAULT true,one_tap_enabled boolean NOT NULL DEFAULT true,email_auth_enabled boolean NOT NULL DEFAULT true,onboarding_require_subjects boolean NOT NULL DEFAULT true,default_daily_goal_hours numeric NOT NULL DEFAULT 4,default_weekly_goal_hours numeric NOT NULL DEFAULT 25,announcement_level text NOT NULL DEFAULT 'info',accent_color text NOT NULL DEFAULT '#2563eb',favicon_url text,logo_url text,push_enabled boolean NOT NULL DEFAULT true,avatar_upload_enabled boolean NOT NULL DEFAULT true,android_min_version text,android_latest_version text,android_update_url text,android_force_update boolean NOT NULL DEFAULT false,updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.app_settings TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.app_settings TO authenticated; GRANT ALL ON public.app_settings TO service_role;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY app_settings_read ON public.app_settings FOR SELECT TO anon,authenticated USING(true);
CREATE POLICY app_settings_admin_write ON public.app_settings FOR ALL TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));

CREATE TABLE public.motivations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),kind text NOT NULL DEFAULT 'quote',title text NOT NULL DEFAULT '',body text NOT NULL DEFAULT '',author text,month smallint,is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.motivations TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.motivations TO authenticated; GRANT ALL ON public.motivations TO service_role;
ALTER TABLE public.motivations ENABLE ROW LEVEL SECURITY;
CREATE POLICY motivations_read ON public.motivations FOR SELECT TO anon,authenticated USING(is_active OR public.has_role(auth.uid(),'admin'));
CREATE POLICY motivations_admin_write ON public.motivations FOR ALL TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));

CREATE TABLE public.avatar_presets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,image_url text NOT NULL,sort_order integer NOT NULL DEFAULT 0,is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.avatar_presets TO authenticated; GRANT ALL ON public.avatar_presets TO service_role;
ALTER TABLE public.avatar_presets ENABLE ROW LEVEL SECURITY;
CREATE POLICY avatar_read ON public.avatar_presets FOR SELECT TO authenticated USING(is_active OR public.has_role(auth.uid(),'admin'));
CREATE POLICY avatar_admin ON public.avatar_presets FOR ALL TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));

CREATE TABLE public.subjects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,name text NOT NULL,color text NOT NULL DEFAULT '#A9C9FF',chapters jsonb NOT NULL DEFAULT '[]',weekly_target_hours numeric NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.subjects TO authenticated; GRANT ALL ON public.subjects TO service_role;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY; CREATE POLICY subjects_own ON public.subjects FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.chapters (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,subject_id uuid NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,name text NOT NULL,position integer NOT NULL DEFAULT 0,difficulty smallint NOT NULL DEFAULT 3,estimated_minutes integer NOT NULL DEFAULT 60,total_units integer,units_done integer NOT NULL DEFAULT 0,first_pass_done boolean NOT NULL DEFAULT false,archived boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(subject_id,name));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.chapters TO authenticated; GRANT ALL ON public.chapters TO service_role;
ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY; CREATE POLICY chapters_own ON public.chapters FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.chapter_subtopics (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,chapter_id uuid NOT NULL REFERENCES public.chapters(id) ON DELETE CASCADE,name text NOT NULL,position integer NOT NULL DEFAULT 0,estimated_minutes integer NOT NULL DEFAULT 30,first_pass_done boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(chapter_id,name));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.chapter_subtopics TO authenticated; GRANT ALL ON public.chapter_subtopics TO service_role;
ALTER TABLE public.chapter_subtopics ENABLE ROW LEVEL SECURITY; CREATE POLICY subtopics_own ON public.chapter_subtopics FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.study_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,subject_id uuid REFERENCES public.subjects(id) ON DELETE SET NULL,subject_name text,chapter text,topic text,category text,kind text NOT NULL DEFAULT 'reading',notes text,started_at timestamptz NOT NULL DEFAULT now(),ended_at timestamptz,planned_end_at timestamptz,is_running boolean NOT NULL DEFAULT true,auto_closed boolean NOT NULL DEFAULT false,break_type text,break_started_at timestamptz,break_minutes integer NOT NULL DEFAULT 0,total_break_seconds integer NOT NULL DEFAULT 0,duration_minutes integer,duration_seconds integer,xp_earned integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),chapter_id uuid REFERENCES public.chapters(id) ON DELETE SET NULL,subtopic_id uuid REFERENCES public.chapter_subtopics(id) ON DELETE SET NULL);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.study_sessions TO authenticated; GRANT ALL ON public.study_sessions TO service_role;
ALTER TABLE public.study_sessions ENABLE ROW LEVEL SECURITY; CREATE POLICY sessions_own ON public.study_sessions FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);
CREATE INDEX study_sessions_user_started_idx ON public.study_sessions(user_id,started_at DESC);

CREATE TABLE public.session_breaks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,session_id uuid REFERENCES public.study_sessions(id) ON DELETE CASCADE,kind text NOT NULL DEFAULT 'free',note text,started_at timestamptz NOT NULL DEFAULT now(),ended_at timestamptz,duration_minutes integer,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.session_breaks TO authenticated; GRANT ALL ON public.session_breaks TO service_role;
ALTER TABLE public.session_breaks ENABLE ROW LEVEL SECURITY; CREATE POLICY breaks_own ON public.session_breaks FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.session_outcomes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,session_id uuid NOT NULL REFERENCES public.study_sessions(id) ON DELETE CASCADE,chapter_id uuid REFERENCES public.chapters(id) ON DELETE SET NULL,subtopic_id uuid REFERENCES public.chapter_subtopics(id) ON DELETE SET NULL,kind text NOT NULL,units_done integer,unit_label text,is_reread boolean NOT NULL DEFAULT false,recall_rating smallint,revision_result text,content_completed_pct smallint,net_focus_minutes integer,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.session_outcomes TO authenticated; GRANT ALL ON public.session_outcomes TO service_role;
ALTER TABLE public.session_outcomes ENABLE ROW LEVEL SECURITY; CREATE POLICY outcomes_own ON public.session_outcomes FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.chapter_learning_state (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,subject_id uuid NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,chapter_name text NOT NULL,review_stage smallint NOT NULL DEFAULT 0,next_review_at timestamptz NOT NULL DEFAULT now()+interval '1 day',last_studied_at timestamptz,reading_minutes integer NOT NULL DEFAULT 0,revision_minutes integer NOT NULL DEFAULT 0,class_minutes integer NOT NULL DEFAULT 0,practice_minutes integer NOT NULL DEFAULT 0,chapter_id uuid REFERENCES public.chapters(id) ON DELETE SET NULL,last_recall smallint,recall_samples integer NOT NULL DEFAULT 0,reading_sessions integer NOT NULL DEFAULT 0,revision_sessions integer NOT NULL DEFAULT 0,class_sessions integer NOT NULL DEFAULT 0,practice_sessions integer NOT NULL DEFAULT 0,first_pass_completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,subject_id,chapter_name));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.chapter_learning_state TO authenticated; GRANT ALL ON public.chapter_learning_state TO service_role;
ALTER TABLE public.chapter_learning_state ENABLE ROW LEVEL SECURITY; CREATE POLICY learning_own ON public.chapter_learning_state FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.targets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,subject_id uuid REFERENCES public.subjects(id) ON DELETE SET NULL,title text NOT NULL,chapters jsonb NOT NULL DEFAULT '[]',deadline date,is_active boolean NOT NULL DEFAULT true,daily_hours numeric NOT NULL DEFAULT 0,weekly_hours numeric NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),chapter_id uuid REFERENCES public.chapters(id) ON DELETE SET NULL);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.targets TO authenticated; GRANT ALL ON public.targets TO service_role;
ALTER TABLE public.targets ENABLE ROW LEVEL SECURITY; CREATE POLICY targets_own ON public.targets FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.subject_targets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,subject_id uuid NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,daily_minutes integer NOT NULL DEFAULT 30,weekly_minutes integer NOT NULL DEFAULT 180,monthly_minutes integer NOT NULL DEFAULT 720,daily_topics integer NOT NULL DEFAULT 1,weekly_topics integer NOT NULL DEFAULT 5,monthly_topics integer NOT NULL DEFAULT 20,daily_chapters integer NOT NULL DEFAULT 0,weekly_chapters integer NOT NULL DEFAULT 1,monthly_chapters integer NOT NULL DEFAULT 4,daily_questions integer NOT NULL DEFAULT 10,weekly_questions integer NOT NULL DEFAULT 60,monthly_questions integer NOT NULL DEFAULT 240,auto_created boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,subject_id));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.subject_targets TO authenticated; GRANT ALL ON public.subject_targets TO service_role;
ALTER TABLE public.subject_targets ENABLE ROW LEVEL SECURITY; CREATE POLICY subject_targets_own ON public.subject_targets FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.timetable_blocks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,subject_id uuid REFERENCES public.subjects(id) ON DELETE SET NULL,title text NOT NULL,kind text NOT NULL DEFAULT 'study',day_of_week integer NOT NULL,start_time time NOT NULL,end_time time NOT NULL,week_parity text NOT NULL DEFAULT 'all',location text,sort_order integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),chapter_id uuid REFERENCES public.chapters(id) ON DELETE SET NULL);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.timetable_blocks TO authenticated; GRANT ALL ON public.timetable_blocks TO service_role;
ALTER TABLE public.timetable_blocks ENABLE ROW LEVEL SECURITY; CREATE POLICY timetable_own ON public.timetable_blocks FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.user_settings (user_id uuid PRIMARY KEY,daily_goal_hours numeric NOT NULL DEFAULT 4,weekly_goal_hours numeric NOT NULL DEFAULT 25,auto_stop_hours numeric NOT NULL DEFAULT 6,week_starts_monday boolean NOT NULL DEFAULT true,ai_tone text NOT NULL DEFAULT 'friendly',ai_autopilot boolean NOT NULL DEFAULT false,widget_layout jsonb NOT NULL DEFAULT '[]',updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.user_settings TO authenticated; GRANT ALL ON public.user_settings TO service_role;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY; CREATE POLICY settings_own ON public.user_settings FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.user_xp (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL UNIQUE,total_xp integer NOT NULL DEFAULT 0,level integer NOT NULL DEFAULT 1,streak integer NOT NULL DEFAULT 0,best_streak integer NOT NULL DEFAULT 0,last_streak_at timestamptz,updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.user_xp TO authenticated; GRANT ALL ON public.user_xp TO service_role;
ALTER TABLE public.user_xp ENABLE ROW LEVEL SECURITY; CREATE POLICY xp_own ON public.user_xp FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.reading_goals (user_id uuid PRIMARY KEY,newspaper_daily_minutes integer NOT NULL DEFAULT 15,magazine_monthly_minutes integer NOT NULL DEFAULT 45,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.reading_goals TO authenticated; GRANT ALL ON public.reading_goals TO service_role;
ALTER TABLE public.reading_goals ENABLE ROW LEVEL SECURITY; CREATE POLICY reading_goals_own ON public.reading_goals FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.reading_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,kind text NOT NULL,log_date date NOT NULL,minutes integer NOT NULL DEFAULT 0,note text,sittings integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,kind,log_date));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.reading_logs TO authenticated; GRANT ALL ON public.reading_logs TO service_role;
ALTER TABLE public.reading_logs ENABLE ROW LEVEL SECURITY; CREATE POLICY reading_logs_own ON public.reading_logs FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.online_classes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,subject_id uuid REFERENCES public.subjects(id) ON DELETE SET NULL,chapter_id uuid REFERENCES public.chapters(id) ON DELETE SET NULL,title text NOT NULL,mode text NOT NULL DEFAULT 'recorded',url text,scheduled_at timestamptz,duration_minutes integer,status text NOT NULL DEFAULT 'scheduled',completed_at timestamptz,chapter_name text,notes_taken boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.online_classes TO authenticated; GRANT ALL ON public.online_classes TO service_role;
ALTER TABLE public.online_classes ENABLE ROW LEVEL SECURITY; CREATE POLICY classes_own ON public.online_classes FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.class_note_revision_state (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,class_id uuid NOT NULL REFERENCES public.online_classes(id) ON DELETE CASCADE,subject_id uuid REFERENCES public.subjects(id) ON DELETE CASCADE,chapter_id uuid REFERENCES public.chapters(id) ON DELETE SET NULL,chapter_name text,title text NOT NULL,review_stage smallint NOT NULL DEFAULT 0,revisions_done integer NOT NULL DEFAULT 0,target_revisions integer NOT NULL DEFAULT 6,next_review_at timestamptz NOT NULL DEFAULT now(),last_revised_at timestamptz,total_minutes integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,class_id));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.class_note_revision_state TO authenticated; GRANT ALL ON public.class_note_revision_state TO service_role;
ALTER TABLE public.class_note_revision_state ENABLE ROW LEVEL SECURITY; CREATE POLICY class_notes_own ON public.class_note_revision_state FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.daily_study_plan_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,plan_date date NOT NULL,subject_id uuid REFERENCES public.subjects(id) ON DELETE SET NULL,chapter_name text,session_kind text NOT NULL DEFAULT 'reading',target_minutes integer NOT NULL,priority smallint NOT NULL DEFAULT 1,source text NOT NULL DEFAULT 'automatic',completed_at timestamptz,completed_session_id uuid REFERENCES public.study_sessions(id) ON DELETE SET NULL,chapter_id uuid REFERENCES public.chapters(id) ON DELETE SET NULL,subtopic_id uuid REFERENCES public.chapter_subtopics(id) ON DELETE SET NULL,pinned boolean NOT NULL DEFAULT false,subject_name text,review_stage smallint,next_review_at timestamptz,scheduled_start time,scheduled_end time,status text NOT NULL DEFAULT 'pending',skipped_at timestamptz,cancelled_at timestamptz,rank_score numeric NOT NULL DEFAULT 0,class_id uuid REFERENCES public.online_classes(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.daily_study_plan_items TO authenticated; GRANT ALL ON public.daily_study_plan_items TO service_role;
ALTER TABLE public.daily_study_plan_items ENABLE ROW LEVEL SECURITY; CREATE POLICY plans_own ON public.daily_study_plan_items FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.test_attempts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,session_id uuid REFERENCES public.study_sessions(id) ON DELETE SET NULL,subject_id uuid REFERENCES public.subjects(id) ON DELETE SET NULL,chapter_id uuid REFERENCES public.chapters(id) ON DELETE SET NULL,subtopic_id uuid REFERENCES public.chapter_subtopics(id) ON DELETE SET NULL,scope text NOT NULL DEFAULT 'chapter',questions_total integer NOT NULL,questions_attempted integer NOT NULL DEFAULT 0,questions_correct integer NOT NULL DEFAULT 0,score numeric,duration_minutes integer,weak_topics text[] NOT NULL DEFAULT '{}',taken_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.test_attempts TO authenticated; GRANT ALL ON public.test_attempts TO service_role;
ALTER TABLE public.test_attempts ENABLE ROW LEVEL SECURITY; CREATE POLICY attempts_own ON public.test_attempts FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,title text NOT NULL,body text,kind text NOT NULL DEFAULT 'info',audience text NOT NULL DEFAULT 'all',action_path text,image_url text,read boolean NOT NULL DEFAULT false,push_sent boolean NOT NULL DEFAULT false,created_by uuid,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.notifications TO authenticated; GRANT ALL ON public.notifications TO service_role;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY; CREATE POLICY notifications_own ON public.notifications FOR ALL TO authenticated USING(auth.uid()=user_id OR public.has_role(auth.uid(),'admin')) WITH CHECK(auth.uid()=user_id OR public.has_role(auth.uid(),'admin'));

CREATE TABLE public.device_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,token text NOT NULL UNIQUE,platform text NOT NULL DEFAULT 'web',device_label text,last_seen_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.device_tokens TO authenticated; GRANT ALL ON public.device_tokens TO service_role;
ALTER TABLE public.device_tokens ENABLE ROW LEVEL SECURITY; CREATE POLICY devices_own ON public.device_tokens FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.ai_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,role text NOT NULL DEFAULT 'user',content text NOT NULL,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.ai_messages TO authenticated; GRANT ALL ON public.ai_messages TO service_role;
ALTER TABLE public.ai_messages ENABLE ROW LEVEL SECURITY; CREATE POLICY ai_own ON public.ai_messages FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.app_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid,event text NOT NULL,path text,platform text,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.app_events TO authenticated; GRANT ALL ON public.app_events TO service_role;
ALTER TABLE public.app_events ENABLE ROW LEVEL SECURITY; CREATE POLICY events_own ON public.app_events FOR SELECT TO authenticated USING(auth.uid()=user_id OR public.has_role(auth.uid(),'admin')); CREATE POLICY events_add ON public.app_events FOR INSERT TO authenticated WITH CHECK(auth.uid()=user_id);

CREATE TABLE public.subject_catalog (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,stream text NOT NULL DEFAULT 'general',color text NOT NULL DEFAULT '#8B5CF6',chapters jsonb NOT NULL DEFAULT '[]',sort_order integer NOT NULL DEFAULT 0,is_active boolean NOT NULL DEFAULT true,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.subject_catalog TO authenticated; GRANT ALL ON public.subject_catalog TO service_role;
ALTER TABLE public.subject_catalog ENABLE ROW LEVEL SECURITY; CREATE POLICY catalog_read ON public.subject_catalog FOR SELECT TO authenticated USING(is_active OR public.has_role(auth.uid(),'admin')); CREATE POLICY catalog_admin ON public.subject_catalog FOR ALL TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));

CREATE TABLE public.legacy_user_claims (email text PRIMARY KEY,payload jsonb NOT NULL,claimed_by uuid,claimed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
GRANT ALL ON public.legacy_user_claims TO service_role;
ALTER TABLE public.legacy_user_claims ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.touch_last_seen() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN UPDATE public.profiles SET last_seen_at=now(),sign_in_count=sign_in_count+1 WHERE id=auth.uid(); END $$;
CREATE OR REPLACE FUNCTION public.log_reading(_kind text,_minutes integer) RETURNS public.reading_logs LANGUAGE plpgsql SET search_path=public AS $$ DECLARE r public.reading_logs; BEGIN IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Not signed in'; END IF; INSERT INTO public.reading_logs(user_id,kind,log_date,minutes,sittings) VALUES(auth.uid(),_kind,CURRENT_DATE,_minutes,1) ON CONFLICT(user_id,kind,log_date) DO UPDATE SET minutes=public.reading_logs.minutes+EXCLUDED.minutes,sittings=public.reading_logs.sittings+1,updated_at=now() RETURNING * INTO r; RETURN r; END $$;
CREATE OR REPLACE FUNCTION public.undo_reading(_kind text) RETURNS void LANGUAGE plpgsql SET search_path=public AS $$ BEGIN DELETE FROM public.reading_logs WHERE user_id=auth.uid() AND kind=_kind AND log_date=CURRENT_DATE; END $$;
CREATE OR REPLACE FUNCTION public.ensure_my_subject_targets() RETURNS integer LANGUAGE plpgsql SET search_path=public AS $$ DECLARE n integer; BEGIN INSERT INTO public.subject_targets(user_id,subject_id,daily_minutes,weekly_minutes,monthly_minutes) SELECT auth.uid(),s.id,GREATEST(1,round(s.weekly_target_hours*60/7)),round(s.weekly_target_hours*60),round(s.weekly_target_hours*60*4) FROM public.subjects s WHERE s.user_id=auth.uid() ON CONFLICT(user_id,subject_id) DO NOTHING; GET DIAGNOSTICS n=ROW_COUNT; RETURN n; END $$;
CREATE OR REPLACE FUNCTION public.set_plan_item_status(_item_id uuid,_status text) RETURNS integer LANGUAGE plpgsql SET search_path=public AS $$ BEGIN UPDATE public.daily_study_plan_items SET status=_status,skipped_at=CASE WHEN _status='skipped' THEN now() ELSE NULL END,cancelled_at=CASE WHEN _status='cancelled' THEN now() ELSE NULL END,updated_at=now() WHERE id=_item_id AND user_id=auth.uid(); RETURN 0; END $$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid,public.app_role),public.touch_last_seen(),public.log_reading(text,integer),public.undo_reading(text),public.ensure_my_subject_targets(),public.set_plan_item_status(uuid,text) TO authenticated;

INSERT INTO public.app_settings(id) VALUES(true) ON CONFLICT DO NOTHING;
INSERT INTO public.motivations(kind,title,body,author) VALUES ('quote','Start small','Success is the sum of small efforts, repeated day in and day out.','Robert Collier'),('quote','Stay curious','The beautiful thing about learning is that no one can take it away from you.','B.B. King');